language: node_js
sudo: false
node_js:
  - 10
before_install:
  - echo "$CLASPRC" > .clasprc.json
  - echo "$CLASPJSON" > .clasp.json
install:
  - npm install
script:
  - npx clasp --version ; cat .clasp.json