language: node_js
sudo: false
node_js:
  - 10
before_install:
  - echo "$CLASPRC" > .clasprc.json
  - echo "$CLASP" > .clasp.json
install:
  - npm install
script:
  echo $test
  # - npx clasp --version ; cat .clasp.json