language: node_js
sudo: false
node_js:
  - 10
before_install:
  - echo "$CLASPRC" > ~/.clasprc.json
  - echo "$CLASP" > .clasp.json
install:
  - npm install
script:
  # - npm run push
  # - echo $CLASP
  # - echo $test
  - clasp settings
  - npx -n "--no-deprecation" clasp pull
  # - npx clasp pull
  # - npx clasp --version ; cat .clasp.json
after_failure:
  - cat $(ls -t /home/travis/.npm/_logs/*-debug.log | head -1)  