language: node_js
sudo: false
node_js:
  - 10
before_install:
  - echo "$CLASPRC" > ~/.clasprc.json
  - echo "$CLASP" > .clasp.json
install:
  - npm install
script:
  # - npm run push
  # - echo $CLASP
  # - echo $test
  - clasp settings
  # - npx clasp --version ; cat .clasp.json